name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend
        run: |
          docker build -t revanthreddyb14/mean-backend:latest backend
          docker push revanthreddyb14/mean-backend:latest

      - name: Build & Push Frontend
        run: |
          docker build -t revanthreddyb14/mean-frontend:latest frontend
          docker push revanthreddyb14/mean-frontend:latest

